var available_orders =
[
    [ "Basic Orders", "basic_orders.html", [
      [ "Auction", "basic_orders.html#auction", null ],
      [ "Discretionary", "basic_orders.html#discretionary", null ],
      [ "Market", "basic_orders.html#market", null ],
      [ "Market If Touched", "basic_orders.html#market_if_touched", null ],
      [ "Market On Close", "basic_orders.html#market_on_close", null ],
      [ "Market On Open", "basic_orders.html#market_on_open", null ],
      [ "Pegged to Market", "basic_orders.html#pegged_market", null ],
      [ "Pegged to Stock", "basic_orders.html#pegged_stock", null ],
      [ "Pegged to Primary", "basic_orders.html#relative_pegged_primary", null ],
      [ "Sweep to Fill", "basic_orders.html#sweep_to_fill", null ],
      [ "Auction Limit", "basic_orders.html#auction_limit", null ],
      [ "Auction Pegged to Stock", "basic_orders.html#auction_pegged_stock", null ],
      [ "Auction Relative", "basic_orders.html#auction_relative", null ],
      [ "Block", "basic_orders.html#block", null ],
      [ "Box Top", "basic_orders.html#boxtop", null ],
      [ "Limit Order", "basic_orders.html#limitorder", null ],
      [ "Forex Cash Quantity Order", "basic_orders.html#limitorderwithcashqty", null ],
      [ "Limit if Touched", "basic_orders.html#limitiftouched", null ],
      [ "Limit on Close", "basic_orders.html#limitonclose", null ],
      [ "Limit on Open", "basic_orders.html#limitonopen", null ],
      [ "Passive Relative", "basic_orders.html#passive_relative", null ],
      [ "Pegged to Midpoint", "basic_orders.html#pegged_midpoint", null ],
      [ "Market to Limit", "basic_orders.html#markettolimit", null ],
      [ "Market with Protection", "basic_orders.html#marketwithprotection", null ],
      [ "Stop", "basic_orders.html#stop", null ],
      [ "Stop Limit", "basic_orders.html#stoplimit", null ],
      [ "Stop with Protection", "basic_orders.html#stopwithprotection", null ],
      [ "Trailing Stop", "basic_orders.html#trailingstop", null ],
      [ "Trailing Stop Limit", "basic_orders.html#trailingstoplimit", null ],
      [ "Combo Limit", "basic_orders.html#combolimit", null ],
      [ "Combo Market", "basic_orders.html#combomarket", null ],
      [ "Combo Limit with Price per Leg", "basic_orders.html#limitordercombolegprices", null ],
      [ "Relative Limit Combo", "basic_orders.html#relativelimitcombo", null ],
      [ "Relative Market Combo", "basic_orders.html#relativemarketcombo", null ],
      [ "Volatility", "basic_orders.html#volatility", null ],
      [ "Pegged to Benchmark", "basic_orders.html#pegged_benchmark", null ]
    ] ],
    [ "Advanced Orders and Algos", "advanced_orders.html", "advanced_orders" ]
];